=head1 Adding a New Project Action

This document describes how to add a new action that can be performed on a
project according to the instructions found in its metadata. If you're looking
to add some other type of command to Plumage, please see
L<Adding a New Command|add-command.pod> instead.

=head2 Base Implementation

You will need to update F<src/lib/Plumage/Project.nqp> to implement the
action, as follows:

=head3 New Subsection

Add a new subsection for the new action within the C<ACTIONS> section of
the code. Try to place the new subsection roughly in the sequence the
action is likely to be used.

=head3 Base Action Method

Add the base action method at the top of the new subsection. It should
be named for the action itself and take no arguments. For instance, the
base method for the C<fetch> action begins C<method fetch() {>. This base
method should start by pulling the action instructions from the metadata.

If these instructions don't exist, most actions should simply report that
the action is not needed or not available on that project and return 1 on
success. A few actions, such as C<fetch> and C<install>, are required and should
return 0 on failure if no instructions exist.

If the instructions do exist, the base method should let the user know
the action is about to be executed and then redispatch to a method
specific to the action type specified in the metadata instructions.

=head3 Specific Action Methods

Add specific action methods for each type supported by the new action.
Each specific method name should have the base method name and the action
type separated by an underscore, e.g. C<fetch_git()> and C<fetch_svn()>.

These should actually perform the task at hand and return 1 on success and 0
on failure.

=head2 Known Actions List

Before the new action is considered valid, it must be added to the known
actions list in the C<known_actions()> method at the top of the C<ACTIONS>
section. Before this is done, metadata referring to the new action will
be considered invalid, and C<perform_actions()> will not recognize new
action.

=head2 Documentation

Add an entry for the new action to the C<SYNOPSIS> section (in the same order
you used when creating the new code section) and then add a section for the new
action with more details in the C<DESCRIPTION> section

=head2 Tests

C<Plumage::Project> does not have a test suite yet.

=head2 Next Steps

Once the new action is implemented, documented, and tested, continue with
L<Adding a New Command|add-command.pod> to add a command for this action to
the C<plumage> command-line tool.
